export const emails = [
  "anika.patel@gmail.com",
  "alex.sanchez@gmail.com",
  "mei.chen@gmail.com",
  "ahmed.khan@gmail.com",
  "isabella.santos@gmail.com",
  "jamal.al-farsi@gmail.com",
  "sofia.costa@gmail.com",
  "rajesh.kapoor@gmail.com",
  "aisha.nguyen@gmail.com",
  "miguel.rodriguez@gmail.com",
  "priya.sharma@gmail.com",
  "kofi.mensah@gmail.com",
  "emma.kim@gmail.com",
  "juan.martinez@gmail.com",
  "yuki.tanaka@gmail.com",
  "ahmed.abdel-malik@gmail.com",
  "maya.patel@gmail.com",
  "amir.khan@gmail.com",
  "leila.abbasi@gmail.com",
  "luca.rossi@gmail.com",
] as const;
