export const people = [
  "Anika Patel",
  "Alex Sanchez",
  "Mei Chen",
  "Ahmed Khan",
  "Isabella Santos",
  "Jamal Al-Farsi",
  "Sofia Costa",
  "Rajesh Kapoor",
  "Aisha Nguyen",
  "Miguel Rodriguez",
  "Priya Sharma",
  "Kofi Mensah",
  "Emma Kim",
  "Juan Martinez",
  "Yuki Tanaka",
  "Ahmed Abdel-Malik",
  "Maya Patel",
  "Amir Khan",
  "Leila Abbasi",
  "Luca Rossi",
] as const;
