export const people = [
  { name: "Anika Patel", email: "anika.patel@gmail.com" },
  { name: "Alex Sanchez", email: "alex.sanchez@gmail.com" },
  { name: "Mei Chen", email: "mei.chen@gmail.com" },
  { name: "Ahmed Khan", email: "ahmed.khan@gmail.com" },
  { name: "Isabella Santos", email: "isabella.santos@gmail.com" },
  { name: "Jamal Al-Farsi", email: "jamal.al-farsi@gmail.com" },
  { name: "Sofia Costa", email: "sofia.costa@gmail.com" },
  { name: "Rajesh Kapoor", email: "rajesh.kapoor@gmail.com" },
  { name: "Aisha Nguyen", email: "aisha.nguyen@gmail.com" },
  { name: "Miguel Rodriguez", email: "miguel.rodriguez@gmail.com" },
  { name: "Priya Sharma", email: "priya.sharma@gmail.com" },
  { name: "Kofi Mensah", email: "kofi.mensah@gmail.com" },
  { name: "Emma Kim", email: "emma.kim@gmail.com" },
  { name: "Juan Martinez", email: "juan.martinez@gmail.com" },
  { name: "Yuki Tanaka", email: "yuki.tanaka@gmail.com" },
  { name: "Ahmed Abdel-Malik", email: "ahmed.abdel-malik@gmail.com" },
  { name: "Maya Patel", email: "maya.patel@gmail.com" },
  { name: "Amir Khan", email: "amir.khan@gmail.com" },
  { name: "Leila Abbasi", email: "leila.abbasi@gmail.com" },
  { name: "Luca Rossi", email: "luca.rossi@gmail.com" },
] as const;
