export const people: { name: string; email: string }[] = [
  { name: "ANIKA PATEL", email: "anika.patel@gmail.com" },
  { name: "ALEX SANCHEZ", email: "alex.sanchez@gmail.com" },
  { name: "MEI CHEN", email: "mei.chen@gmail.com" },
  { name: "AHMED KHAN", email: "ahmed.khan@gmail.com" },
  { name: "ISABELLA SANTOS", email: "isabella.santos@gmail.com" },
  { name: "JAMAL AL-FARSI", email: "jamal.al-farsi@gmail.com" },
  { name: "SOFIA COSTA", email: "sofia.costa@gmail.com" },
  { name: "RAJESH KAPOOR", email: "rajesh.kapoor@gmail.com" },
  { name: "AISHA NGUYEN", email: "aisha.nguyen@gmail.com" },
  { name: "MIGUEL RODRIGUEZ", email: "miguel.rodriguez@gmail.com" },
  { name: "PRIYA SHARMA", email: "priya.sharma@gmail.com" },
  { name: "KOFI MENSAH", email: "kofi.mensah@gmail.com" },
  { name: "EMMA KIM", email: "emma.kim@gmail.com" },
  { name: "JUAN MARTINEZ", email: "juan.martinez@gmail.com" },
  { name: "YUKI TANAKA", email: "yuki.tanaka@gmail.com" },
  { name: "AHMED ABDEL-MALIK", email: "ahmed.abdel-malik@gmail.com" },
  { name: "MAYA PATEL", email: "maya.patel@gmail.com" },
  { name: "AMIR KHAN", email: "amir.khan@gmail.com" },
  { name: "LEILA ABBASI", email: "leila.abbasi@gmail.com" },
  { name: "LUCA ROSSI", email: "luca.rossi@gmail.com" },
] as const;
