export const people = [
  { name: "ANIKA PATEL", email: "anika.patel@gmail.com", age: 57 },
  {
    name: "ALEJANDRO FERNANDEZ",
    email: "alejandro.fernandez@gmail.com",
    age: 34,
  },
  { name: "MEI CHEN", email: "mei.chen@gmail.com", age: 72 },
  { name: "AHMED KHAN", email: "ahmed.khan@gmail.com", age: 41 },
  { name: "ISABELLA SANTOS", email: "isabella.santos@gmail.com", age: 20 },
  { name: "JAMAL AL-FARSI", email: "jamal.al-farsi@gmail.com", age: 61 },
  { name: "SOFIA COSTA", email: "sofia.costa@gmail.com", age: 1 },
  { name: "RAJESH KAPOOR", email: "rajesh.kapoor@gmail.com", age: 49 },
  { name: "AISHA NGUYEN", email: "aisha.nguyen@gmail.com", age: 78 },
  { name: "MIGUEL RODRIGUEZ", email: "miguel.rodriguez@gmail.com", age: 68 },
  { name: "PRIYA SHARMA", email: "priya.sharma@gmail.com", age: 25 },
  { name: "KOFI MENSAH", email: "kofi.mensah@gmail.com", age: 82 },
  { name: "EMMA KIM", email: "emma.kim@gmail.com", age: 8 },
  { name: "JUAN MARTINEZ", email: "juan.martinez@gmail.com", age: 63 },
  { name: "YUKI TANAKA", email: "yuki.tanaka@gmail.com", age: 30 },
  { name: "AHMED ABDEL-MALIK", email: "ahmed.abdel-malik@gmail.com", age: 69 },
  { name: "MAYA PATEL", email: "maya.patel@gmail.com", age: 46 },
  { name: "AMIR KHAN", email: "amir.khan@gmail.com", age: 79 },
  { name: "LEILA ABBASI", email: "leila.abbasi@gmail.com", age: 40 },
  { name: "LUCA ROSSI", email: "luca.rossi@gmail.com", age: 21 },
];
